name: Release native launchers
on:
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:

jobs:
  ping-sbtn-dist:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Notify sbt/sbtn-dist of new sbt release
      if: github.event.action != 'ACKNewSbtVersion'
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rochala/sbtn-dist/dispatches \
          -d '{"event_type":"NewSbtVersionReleased","client_payload":{"repository": "rochala/sbt" }}'
    - name: ACK - sbt/sbtn-dist confirmed new release
      if: github.event.action == 'ACKNewSbtVersion'
      run: |
        echo "ACK received from '${{ github.event.client_payload.repository }}'" && \
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rochala/sbtn-dist/dispatches \
          -d '{"event_type":"AutomaticRelease","client_payload":{"version": "${{ github.ref }}"}}'

