name: Publish to WinGet
on: workflow_dispatch
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: sbt.sbt
          token: ${{ secrets.WINGET_TOKEN }}
